---
- name: Docker Config
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Remove Containers
     shell: docker rm $(docker ps -a -q) -f || true

   - name: Start Postgres 11.6 Container
     shell: docker run --name database-debug -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres:11.6

   - name: Docker Prune Job
     cron:
      name: docker prune
      hour: "02"
      job: docker system prune -f
      cron_file: docker_prune
      user: vagrant
