---
- name: Git Config
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_user: vagrant
  tasks:

   - name: "Configure Git Global"
     command: "git config --global {{ item }}"
     with_items:
      - user.name ${GIT_NAME}
      - user.email ${GIT_EMAIL}
      - alias.pretty log --pretty=oneline --abbrev-commit -n 10

   - name: Check for Secrets Baseline
     local_action: stat path=.secrets.baseline
     register: secrets_baseline

   - name: Get Secrets Basline
     when: secrets_baseline.stat.exists == false
     command: detect-secrets scan > .secrets.baseline

   - name: "Install Git Hooks"
     command: pre-commit install
