---
- name: Git Config
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_user: vagrant
  tasks:

   - name: Add Git Ignores
     copy:
      remote_src: no
      src: ~/project/vm/config/git/.gitignore_global
      dest: ~/.gitignore_global

   - name: "Add Commit Template"
     copy:
      remote_src: yes
      src: ~/project/vm/config/git/.gitmessage.txt
      dest: ~/.gitmessage.txt

   - name: "Configure Git Name"
     command: git config --global user.name ${GIT_NAME}

   - name: "Configure Git Email"
     command: git config --global user.email ${GIT_EMAIL}

   - name: "Configure Git Editor"
     command: git config --global core.editor nano

   - name: "Configure Git Excludes"
     command: git config --global core.excludesfile ~/.gitignore_global

   - name: "Configure Git Messages"
     command: git config --global commit.template ~/.gitmessage.txt

   - name: "Add Git Alias (git pretty)"
     command: git config --global alias.pretty "!git log --pretty=oneline --abbrev-commit -n 10"

   - name: "Add Git Alias (git force)"
     command: git config --global alias.force "!git push origin +$(git rev-parse --abbrev-ref HEAD)"

   - name: "Install Git Hooks"
     command: pre-commit install
