---
- name: k8s Config
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Enable Microk8s Services
     command: "microk8s enable {{ item }}"
     with_items:
      - registry
      - dns

   - name: Add Octant Service
     copy:
      remote_src: yes
      src: /home/vagrant/project/vm/config/octant/octant.service
      dest: /etc/systemd/system/octant.service
      owner: root

   - name: Start Octant Service
     systemd:
      name: octant.service
      daemon_reload: yes
      enabled: yes
      state: started
