---
- name: Proxy Config
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Remove Default Config
     file:
      path: /etc/nginx/sites-enabled/default
      state: absent

   - name: Create TLS Directory
     file:
       path: /tls
       state: directory
       mode: '0755'

   - name: Uninstall Root CA
     command: mkcert -uninstall

   - name: Install Root CA
     command: mkcert -install

   - name: Generate Certificates
     command: mkcert -cert-file /tls/delineate.local.crt -key-file /tls/delineate.local.key "delineate.local" localhost 127.0.0.1 ::1

   - name: Copy NGINX Config
     copy:
      src: /home/vagrant/project/vm/config/nginx/nginx.conf
      dest: /etc/nginx/sites-enabled/nginx.conf

   - name: Start NGINX Service
     systemd:
      name:  nginx.service
      scope: system
      enabled: yes
      state: restarted
     become_user: root

   - name: Copy Certificate
     copy:
      remote_src: yes
      src: /root/.local/share/mkcert/rootCA.pem
      dest: /home/vagrant/project/vm/config/nginx/rootCA.pem
