---
- name: Starship Config
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Create Starship Directory
     file:
       path: ~/.config
       state: directory
       mode: '0755'
     become_user: vagrant

   - name: Adds Starship Config
     copy:
      remote_src: yes
      src: ~/project/vm/config/starship/starship.toml
      dest: ~/.config/starship.toml
     become_user: vagrant
