---
- name: Bootstrap
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

# add file -----------------------------------------------------------

   - name: Add files
     copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      remote_src: false
     with_items:
      - { name: .env, src: ./.env, dest: ~/.env }
     loop_control:
      label: '{{ item.name }}'
     become_user: vagrant

# terraform ----------------------------------------------------------

   - name: Downgrade Terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
       dest: /usr/local/bin/
       remote_src: yes
     become_user: root
