version: 2.1
orbs:

  welcome: circleci/welcome-orb@0.4.1
  snyk: snyk/snyk@0.0.10
  gcloud: circleci/gcp-cli@1.8.4
  kubernetes: circleci/kubernetes@0.11.0
  shellcheck: circleci/shellcheck@1.3.16
  go: circleci/go@1.2.0

jobs:
  build: welcome/run
  scan:
    docker:
      - image: 'circleci/buildpack-deps:stretch'
    environment:
      IMAGE_NAME: docker/whalesay
    steps:
      - setup_remote_docker
      - run: docker pull $IMAGE_NAME
      - run: docker run -d $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

workflows:
  version: 2
  scan_images:
    jobs:
      - build
      - scan

# https://circleci.com/docs/2.0/using-orbs/
#

# docker pull docker/whalesay
