version: 2.1

jobs:
  infra:
    docker:
      - image: hashicorp/terraform:0.12.26
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcp.json
    steps:
      - checkout
      - run: echo $GCP_KEY >> /gcp.json
      - run: cd ./ops/cloud && terraform init -backend-config="bucket=${GCP_PROJECT}-tf"
      - run: cd ./ops/cloud && terraform apply -var="gcp_project=${GCP_PROJECT}" -lock=true -refresh=true -auto-approve

workflows:
  version: 2
  run:
    jobs:
      - infra
