version: 2.1

jobs:
  infra:
    docker:
      - image: hashicorp/terraform:0.12.26
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcp.json
    steps:
      - checkout
      - run: echo $GCP_KEY >> /gcp.json
      - run: cd ./ops && terraform init -backend=true
      - run: cd ./ops && terraform apply -lock=true -refresh=true -auto-approve

workflows:
  version: 2
  run:
    jobs:
      - infra
