apiVersion: v1
kind: Service
metadata:
  name: customers
  # This links the security policy that all traffic must have come
  # from Cloudflare
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"backend-config"}}'
spec:
  ports:
  - port: 80
    targetPort: 1102
    protocol: TCP
  selector:
    run: customers
  type: NodePort
