apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: customers
  insecureRegistries:
  - localhost:32000

test:
  - image: customers
    structureTests:
      - structure.yml
deploy:
  kubectl:
    manifests:
      - k8s/*
profiles:
- name: local # Local k8s
- name: dev # Unrestricted Cloud dev env
- name: staging # Only via the pipeline
- name: prod # Only via the pipeline
