apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: customers
    # TODO: Docker build args is only supported beta
    #docker:
    #  buildArgs:
    #    - MAINTAINER=jonathan.fenwick@delineate.io
    #    - BUILD_DATE=2020-06-15T19:23:05Z
    #    - VCS_REF=039f80a
test:
  - image: customers
    structureTests:
      - structure.yml
deploy:
  kubectl:
    manifests:
      - k8s/*
profiles:
- name: local
  activation:
    - kubeContext: local
      command: dev
- name: staging
  activation:
    - kubeContext: staging
      command: run
