@baseUrl = https://api.delineate.dev

GET {{baseUrl}}/healthz HTTP/2
content-type: application/json

###

POST {{baseUrl}}/customer HTTP/2
content-type: application/json

{
    "forename": "jonathan",
    "surname": "fenwick"
}
