---
- name: CLI Install
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Install Terraform
     when: ansible_local.terraform.installed == false
     shell: |
      mkdir -p ~/hashicorp
      cd ~/hashicorp
      wget "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip"
      unzip "terraform_0.12.29_linux_amd64.zip"
      sudo install "terraform" /usr/local/bin/
     args:
      warn: false

   - name: Install Http
     snap:
      name: http
      channel: latest/stable
      state: present

   - name: Install Snyk
     npm:
      name: snyk
      version: 1.346.0
      global: yes

   - name: Install Trivy
     apt:
      deb: https://github.com/aquasecurity/trivy/releases/download/v0.9.1/trivy_0.9.1_Linux-64bit.deb

   - name: Install CircleCI
     shell:
      curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
     args:
      warn: false

   - name: Install PSQL
     apt:
      name: postgresql-client=10+190ubuntu0.1
      state: present

   - name: Install JQ
     apt:
      name: jq=1.5+dfsg-2
      state: present

   # Hack - Ensure there is a usable
   # https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml
   - name: Install PyYAML
     pip:
      name: PyYAML==5.3.1
      extra_args: --ignore-installed

   - name: Install Pre-Commit
     when: ansible_local.pre_commit.installed == false
     pip:
      name: pre-commit==2.5.1

   - name: Install Shellcheck
     apt:
      name: shellcheck=0.4.6-1
      state: present

   - name: Install Detect Secrets
     pip:
      name: detect-secrets==0.13.1

   - name: Install InSpec
     gem:
      name: inspec-bin
      version: 4.21.3
      state: present
     become_user: vagrant

   - name: Download Starship
     when: ansible_local.starship.installed == false
     command: wget -P ~/starship https://starship.rs/install.sh
     become_user: vagrant
     args:
      warn: false

   - name: Install Starship
     when: ansible_local.starship.installed == false
     command: bash ~/starship/install.sh --yes
     become_user: vagrant
