---
- name: Cloud Install
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   # TODO: This needs to be locked to a specific version - this could drift!
   # https://cloud.google.com/sdk/docs/downloads-versioned-archives
   - name: Install GCloud
     when: ansible_local.gcloud.installed == false
     shell: |
        cd ~/
        curl https://sdk.cloud.google.com > install.sh
        bash install.sh --disable-prompts
     become_user: vagrant

   # install via gcloud for version alignment
   - name: Install Skaffold
     when: ansible_local.skaffold.installed == false
     command: gcloud components install skaffold --quiet
     become_user: vagrant

   - name: Install Structure Test
     when: ansible_local.structure.installed == false
     get_url:
      url: https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
      dest: /usr/local/bin/container-structure-test
      mode: '0775'

   # install via kubectl for version alignment
   - name: Install Kubectl
     when: ansible_local.kubectl.installed == false
     command: gcloud components install kubectl --quiet
     become_user: vagrant

   - name: Install Octant
     apt:
      deb: https://github.com/vmware-tanzu/octant/releases/download/v0.13.1/octant_0.13.1_Linux-64bit.deb
