---
- name: Docker Install
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Add Docker Key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Add Docker Repo
     apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present

   - name: Install Docker
     apt:
      pkg: docker-ce=5:19.03.12~3-0~ubuntu-bionic
      update_cache: yes

   - name: Start Docker Service
     systemd:
      name: docker.service
      daemon_reload: yes
      enabled: yes
      state: started

   - name: Create Docker Group
     group:
      name: docker
      state: present

   - name: Add to Docker Group
     user:
      name: vagrant
      groups: docker
      append: yes
