---
- name: Profile Install
  connection: local
  gather_facts: false
  hosts: all
  vars:
    sudors:
      vagrant
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_user: vagrant
  tasks:

   - name: Adds Bash Profile
     copy:
      remote_src: yes
      src: ~/project/vm/install/files/.bash_profile
      dest: ~/.bash_profile
      mode: 777
     become_user: vagrant
