---
- name: Docker Install
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Install Docker Pip
     pip:
      name: docker==4.2.1

   - name: Install Docker
     snap:
      name: docker
      channel: latest/stable
      state: present

   - name: Create Docker Group
     group:
      name: docker
      state: present

   - name: Add to Docker Group
     user:
      name: vagrant
      groups: docker
      append: yes

   - name: Install Docker-Compose
     apt:
      pkg:
       - docker-compose=1.17.1-2
      state: present
