---
- name: Git Install
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_user: vagrant
  tasks:

   - name: Check for ~/.gitignore_global
     local_action: stat path=~/.gitignore_global
     register: gitignore_global

   - name: Add Git Ignores
     when: gitignore_global.stat.exists == false
     copy:
      remote_src: no
      src: ./files/.gitignore_global
      dest: ~/.gitignore_global

   - name: Check for ~/.gitconfig
     local_action: stat path=~/.gitconfig
     register: gitconfig

   - name: "Configure Git Global"
     when: gitconfig.stat.exists == false
     command: "git config --global {{ item }}"
     with_items:
      - core.editor nano
      - core.excludesfile ~/.gitignore_global
      - commit.template ~/.gitmessage.txt

   - name: Check for ~/.gitmessage.txt
     local_action: stat path=~/.gitmessage.txt
     register: gitmessage

   - name: "Add Commit Template"
     when: gitmessage.stat.exists == false
     copy:
      remote_src: yes
      src: ./files/.gitmessage.txt
      dest: ~/.gitmessage.txt

   - name: Install Pre-Commit Pip
     when: ansible_local.pre_commit.installed == false
     pip:
      name: pre-commit==2.5.1

   - name: Install Detect Secrets
     pip:
      name: detect-secrets==0.13.1
