---
- name: Go Install
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Install Go
     snap:
      name: go
      channel: 1.14/stable
      classic: true
      state: present

   - name: Install golangci
     when: ansible_local.golangci.installed == false
     shell: |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
