---
- name: k8s Install
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Install Microk8s
     snap:
      name:
        - microk8s
      channel: 1.18/stable
      classic: true
      state: present

   - name: Add to Microk8s Group
     user:
      name: vagrant
      groups: microk8s
      append: yes

   - name: Open Firewall
     command: iptables -P FORWARD ACCEPT

   - name: Install Kubectx
     get_url:
      url: https://github.com/ahmetb/kubectx/releases/download/v0.9.1/kubectx
      dest: /usr/local/bin/kubectx
      mode: '0775'

   - name: Install Kubens
     get_url:
      url: https://github.com/ahmetb/kubectx/releases/download/v0.9.1/kubens
      dest: /usr/local/bin/kubens
      mode: '0775'

   - name: Install Octant
     apt:
      deb: https://github.com/vmware-tanzu/octant/releases/download/v0.13.1/octant_0.13.1_Linux-64bit.deb
