---
- name: Proxy Install
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

   - name: Install Caddy
     apt:
      deb: https://github.com/caddyserver/caddy/releases/download/v2.1.1/caddy_2.1.1_linux_amd64.deb

   - name: Create Caddy Group
     group:
      name: caddy
      system: yes
      state: present

   - name: Add Caddy User
     user:
      name: caddy
      shell: /usr/sbin/nologin
      create_home: yes
      home: /var/lib/caddy
      group: caddy
      groups: caddy
      append: yes

   - name: Add Caddy User to Sudoers
     blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: "caddy   ALL=(ALL) NOPASSWD: ALL"
      dest: /etc/sudoers
