prompt_order = [
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "golang",
    "java",
    "julia",
    "nim",
    "nodejs",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "aws",
    "line_break",
    "character",
]
