server:
  port: 8080
  mode: debug
  timeouts:
    read: 15s
    write: 15s
    hammer: 30m
logging:
  level: debug
db:
  customers:
    type: postgres
    connection: postgres://postgres:postgres@database-stack:5432/postgres?sslmode=disable
    limits:
      maxIdle: 5
      maxOpen: 100
      maxLifetime: 1h
    retries:
      attempts: 5
      delay: 100ms