version: "3.7"

services:

  # https://itnext.io/wildcard-lets-encrypt-certificate-2b6133a1acdf
  # https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-18-04#conclusion
  customers:
    container_name: customers-stack
    image: customers:${STACK_TAG}-stack
    build:
      context: ../services/customers
      args:
        MAINTAINER: ${STACK_MAINTAINER}
        ENV: stack
        LOCATION: /config
        BUILD_DATE: ${STACK_BUILD_DATE}
        VCS_REF: ${STACK_VCS_REF}
    ports:
      - 8081:8080
    environment:
      - ENV=${STACK_ENV}
      - LOCATION=${STACK_LOCATION}
    restart: always
    links:
      - database
    depends_on:
      - database

  database:
    container_name: database-stack
    image: postgres:11.6
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
