---
- name: Docker
  connection: local
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    sudoers:
      - vagrant
  become: true
  tasks: 

   - name: Install Docker Pip
     pip:
      name: docker==4.2.1

   - name: Install Docker
     snap:
      name: docker
      channel: latest/stable
      state: present

   - name: Create Docker Group
     group:
      name: docker
      state: present

   - name: Add to Docker Group
     user:
      name: vagrant
      groups: docker
      append: yes
        
   - name: Install Docker-Compose
     apt:
      pkg:
       - docker-compose=1.17.1-2
      state: present

   - name: Start Postgres 11.6 Container
     docker_container:
      name: database-dev
      image: postgres:11.6
      state: started
      recreate: yes
      restart: yes
      ports:
        - 5432:5432
      env:
        POSTGRES_PASSWORD: "postgres"

   - name: Docker Prune Job
     cron:
      name: docker prune
      hour: "02"
      job: docker system prune -f
      cron_file: docker_prune
      user: vagrant
