---
- name: Facts
  connection: local
  gather_facts: false
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true

  tasks:
   - name: "Add Facts Directory"
     file:
      path: "/etc/ansible/facts.d"
      state: directory
      owner: vagrant

   - name: "Add Facts"
     copy:
      remote_src: yes
      src: ~/project/ansible/facts/
      dest: /etc/ansible/facts.d
     become_user: vagrant

   - name: "Make Facts Executable"
     command: chmod -R +x /etc/ansible/facts.d
     args:
      warn: no

   - name: "Refresh Facts"
     setup: ~
