---
- name: Profile
  connection: local
  gather_facts: false
  hosts: all
  vars:
    sudors:
      vagrant
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_user: vagrant
  tasks:

   - name: Check for ~/bash_profile
     local_action: stat path=~/.bash_profile
     register: profile

   - name: Adds Bash Profile
     when: profile.stat.exists == false
     copy:
      remote_src: yes
      src: /files/.bash_profile
      dest: ~/.bash_profile
     become_user: vagrant

   - name: Add Git Env
     when: profile.stat.exists == false
     blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK GIT"
      block: "{{ lookup('file', '~/project/.env/git.env') }}"
      dest: ~/.bash_profile

   - name: Add Google Env
     when: profile.stat.exists == false
     blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK GOOGLE"
      block: "{{ lookup('file', '~/project/.env/google.env') }}"
      dest: ~/.bash_profile

   - name: Add Cloudflare Env
     when: profile.stat.exists == false
     blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK CLOUDFLARE"
      block: "{{ lookup('file', '~/project/.env/cloudflare.env') }}"
      dest: ~/.bash_profile

   - name: Add Snyk Env
     when: profile.stat.exists == false
     blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK SNYK"
      block: "{{ lookup('file', '~/project/.env/snyk.env') }}"
      dest: ~/.bash_profile
